" Originally based on ivim, gradually diverging.
" https://github.com/kepbod/ivim

"
" General
"
set nocompatible
filetype plugin indent on
set timeoutlen=500
set autoread
set hidden
set history=1000
set modeline
set encoding=utf-8
set completeopt+=longest
set completeopt-=preview

"" Source the vimrc file after saving it
autocmd BufWritePost $MYVIMRC source $MYVIMRC
autocmd BufWritePost $MYVIMRC NeoBundleClean
"" Fast edit the .vimrc file using \x
nnoremap <Leader>x :tabedit $MYVIMRC<CR>

"
" NeoBundle
"
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.dotfiles/vendor/neobundle.vim/
endif
call neobundle#begin(expand($HOME . '/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

""
"" Start Bundles

"" Interface Bundles
NeoBundle 'w0ng/vim-hybrid'
NeoBundle 'bling/vim-airline'
NeoBundle 'bling/vim-bufferline'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'mhinz/vim-startify'
NeoBundle 'junegunn/goyo.vim' " Distraction-free editing
NeoBundle 'junegunn/limelight.vim' " Hyperfocus-writing

"" Enhancement Bundles
NeoBundle 'Raimondi/delimitMate'
NeoBundle 'scrooloose/nerdcommenter'
NeoBundle 'tpope/vim-abolish'
NeoBundle 'tpope/vim-speeddating'
NeoBundle 'tpope/vim-repeat'
NeoBundle 'tpope/vim-surround'
NeoBundle 'kristijanhusak/vim-multiple-cursors'
NeoBundle 'mbbill/undotree'
NeoBundle 'godlygeek/tabular'
NeoBundle 'sickill/vim-pasta'
NeoBundle 'Keithbsmiley/investigate.vim'
NeoBundle 'wellle/targets.vim'
NeoBundle 'roman/golden-ratio'
NeoBundle 'chrisbra/vim-diff-enhanced'
NeoBundle 'Shougo/vimproc', {
            \ 'build' : {
            \     'windows' : 'make -f make_mingw32.mak',
            \     'cygwin' : 'make -f make_cygwin.mak',
            \     'mac' : 'make -f make_mac.mak',
            \     'unix' : 'make -f make_unix.mak',
            \    },
            \ }

"" Movement Bundles
NeoBundle 'tpope/vim-unimpaired'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'bkad/CamelCaseMotion'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'edsono/vim-matchit'

"" Navigation Bundles
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/unite-outline'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'jistr/vim-nerdtree-tabs'

"" Autocompletion Bundles
if has('lua')
  NeoBundle 'Shougo/neocomplete.vim'
  let g:completion_engine='neocomplete'
else
  NeoBundle 'Shougo/neocomplcache.vim'
  let g:completion_engine='neocomplcache'
endif
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'

"" Build Bundles
NeoBundle 'scrooloose/syntastic'

"" Version Control Bundles
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'airblade/vim-gitgutter'

"" End Bundles
""

call neobundle#end()
NeoBundleCheck

"
" Interface
"
set title
set titlestring=%t%(\ %m%)%(\ (%{expand('%:p:h')})%)%(\ %a%)
set wildmenu
set wildmode=full
set backspace=indent,eol,start
set whichwrap+=h,l,<,>,[,]
set scrolljump=5 " Lines to jump when scrolling off-screen
set scrolloff=3 " Minimum number of lines to keep above and below cursor
set sidescroll=1 " Minimal number of columns to scroll horizontally
set sidescrolloff=10 " Minimal number of screen columns to keep away from cursor
set showmatch " Show matching brackets/parenthesis
set matchtime=2 " Decrease the time to blink
set number " Show line numbers
nnoremap <Leader>n :set relativenumber!<CR> " Toggle relative line numbers
set formatoptions+=rnlmM
"set wrap
set textwidth=80

"
" Colors and Fonts
"
syntax on
colorscheme hybrid
set background=dark
set list " Visible whitespace
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮
set linebreak
set showbreak=↪
set fillchars=diff:⣿,vert:│

"
" Indentation
"
set autoindent
set cindent
set expandtab
set softtabstop=2
set shiftwidth=2
set shiftround

"
" Search
"
set ignorecase
set smartcase
set hlsearch
set incsearch
set gdefault " Default g flag
nnoremap / /\v
vnoremap / /\v
nnoremap <Leader><Space> :set hlsearch!<CR> " Use \<Space> to toggle search highlighting

"
" Filetype Settings
"

" quickfix
augroup ft_quickfix
  autocmd!
  autocmd filetype qf setlocal nolist nocursorline nowrap textwidth=0
augroup end

" markdown
augroup ft_markdown
  autocmd!
  " use <Leader>1/2/3/4/5/6 to add headings
  autocmd filetype markdown nnoremap <buffer> <Leader>1 I# <ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>2 I## <ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>3 I### <ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>4 I#### <ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>5 I##### <ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>6 I###### <ESC>
  " use <Leader>b to add blockquotes in normal and visual mode
  autocmd filetype markdown nnoremap <buffer> <Leader>b I> <ESC>
  autocmd filetype markdown vnoremap <buffer> <Leader>b :s/^/> /<CR>
  " use <Leader>ul and <Leader>ol to add list symbols in visual mode
  autocmd filetype markdown vnoremap <buffer> <Leader>ul :s/^/* /<CR>
  autocmd filetype markdown vnoremap <buffer> <Leader>ol :s/^/\=(line(".")-line("'<")+1).'. '/<CR>
  " use <Leader>e1/2/3 to add emphasis symbols
  autocmd filetype markdown nnoremap <buffer> <Leader>e1 I*<ESC>a*<ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>e2 I**<ESC>a**<ESC>
  autocmd filetype markdown nnoremap <buffer> <Leader>e3 I***<ESC>a***<ESC>
  autocmd filetype markdown vnoremap <buffer> <Leader>e1 :s/\%v\(.*\)\%v/\*\1\*/<CR>
  autocmd filetype markdown vnoremap <buffer> <Leader>e2 :s/\%v\(.*\)\%v/\*\*\1\*\*/<CR>
  autocmd filetype markdown vnoremap <buffer> <Leader>e3 :s/\%V\(.*\)\%V/\*\*\*\1\*\*\*/<CR>
  " Turn on spell
  autocmd filetype markdown setlocal spell
augroup END

" HTML
augroup ft_html
  autocmd!
  autocmd filetype html setlocal spell
augroup END

"
" Key Mappings
"

"" Window navigation
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

"" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

"" Repeat last substitution, including flags, with &.
nnoremap & :&&<CR>
xnoremap & :&&<CR>

"" Select entire buffer
nnoremap vaa ggvGg_

"" Strip all trailing whitespace in the current file
nnoremap <Leader>q :%s/\s\+$//<CR>:let @/=''<CR>

"" Fix all indents
nnoremap <Leader>= gg=G

"" Wrap Current Paragraph
nnoremap <Leader>q vipgq

"" Toggle Spellcheck
nnoremap <Leader>s :set spell!<CR>

"" Toggle paste mode
set pastetoggle=<F2>

"" Remove last search highlight
nnoremap <F3> :noh<CR>

"
" Plugin Settings
"

"" Indent Guides
let g:indent_guides_auto_colors=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=235
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=235
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_guide_size=1
let g:indent_guides_default_mapping=0
let g:indent_guides_exclude_filetypes=['help', 'nerdtree', 'startify', 'markdown']

"" Startify
let g:startify_custom_header=[
  \'            (       *     ',
  \'            )\ )  (  `    ',
  \'    (   (  (()/(  )\))(   ',
  \'    )\  )\  /(_))((_)()\  ',
  \'   ((_)((_)(_))  (_()((_) ',
  \'   \ \ / / |_ _| |  \/  | ',
  \'    \ V /   | |  | |\/| | ',
  \'     \_/   |___| |_|  |_| ',
  \'                          ']
hi StartifyHeader  ctermfg=111
hi StartifyFooter  ctermfg=111
hi StartifyBracket ctermfg=240
hi StartifyNumber  ctermfg=215
hi StartifyPath    ctermfg=245
hi StartifySlash   ctermfg=240

"" Goyo and Limelight
let g:limelight_conceal_ctermfg = 'gray'
let g:limelight_conceal_ctermfg = 240
autocmd User GoyoEnter Limelight
autocmd User GoyoLeave Limelight!

"" delimitMate
let delimitMate_expand_cr = 1
let delimitMate_expand_space=1
let delimitMate_balance_matchpairs=1

"" NERD commenter
let NERDCommentWholeLinesInVMode=2
let NERDSpaceDelims=1
let NERDRemoveExtraSpaces=1

"" Multiple Cursors
" Disable multiple cursors during NeoComplete.
function! Multiple_cursors_before()
  if g:ivim_completion_engine=='neocomplete'
    exe 'NeoCompleteLock'
  else
    exe 'NeoComplCacheLock'
  endif
endfunction
function! Multiple_cursors_after()
  if g:ivim_completion_engine=='neocomplete'
    exe 'NeoCompleteUnlock'
  else
    exe 'NeoComplCacheUnlock'
  endif
endfunction

"" Undo Tree
nnoremap <Leader>u :UndotreeToggle<CR>
let g:undotree_SetFocusWhenToggle=1

"" investigate.vim
nnoremap <Leader>k :call investigate#Investigate()<CR>

"" Tag Bar
nnoremap <Leader>t :TagbarToggle<CR>
let g:tagbar_autofocus=1
let g:tagbar_expand=1
let g:tagbar_foldlevel=2
let g:tagbar_autoshowtag=1

"" Unite
" See https://github.com/kepbod/ivim/blob/762ff3556c2251d1c997d683c0363e6680d4a9dc/vimrc#L734

"" NERD tree
nnoremap <Leader>d :NERDTreeTabsToggle<CR>
nnoremap <Leader>f :NERDTreeFind<CR> " Highlight current file in NERD tree
let NERDTreeChDirMode=2
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1
let NERDTreeShowLineNumbers=1
let NERDTreeDirArrows=1

""  Neocomplete & Neocomplcache
" Use Tab and S-Tab to select candidate
inoremap <expr><Tab>  pumvisible() ? "\<C-N>" : "\<Tab>"
inoremap <expr><S-Tab> pumvisible() ? "\<C-P>" : "\<S-Tab>"
if g:completion_engine=='neocomplete'
  let g:neocomplete#enable_at_startup=1
  let g:neocomplete#data_directory=$HOME . '/.vim/cache/neocomplete'
  let g:neocomplete#enable_auto_delimiter=1
  " Use <C-E> to close popup
  inoremap <expr><C-E> neocomplete#cancel_popup()
  inoremap <expr><CR> delimitMate#WithinEmptyPair() ?
              \ "\<C-R>=delimitMate#ExpandReturn()\<CR>" :
              \ pumvisible() ? neocomplete#close_popup() : "\<CR>"
else
  let g:neocomplcache_enable_at_startup=1
  let g:neocomplcache_temporary_dir=$HOME . '/.vim/cache/neocomplcache'
  let g:neocomplcache_enable_auto_delimiter=1
  let g:neocomplcache_enable_fuzzy_completion=1
  " Use <C-E> to close popup
  inoremap <expr><C-E> neocomplcache#cancel_popup()
  inoremap <expr><CR> delimitMate#WithinEmptyPair() ?
              \ "\<C-R>=delimitMate#ExpandReturn()\<CR>" :
              \ pumvisible() ? neocomplcache#close_popup() : "\<CR>"
endif

"" Neosnippet
" Set information for snippets
let g:neosnippet#enable_snipmate_compatibility=1
" Use <C-K> to expand or jump snippets in insert mode
imap <C-K> <Plug>(neosnippet_expand_or_jump)
" Use <C-K> to replace TARGET within snippets in visual mode
xmap <C-K> <Plug>(neosnippet_start_unite_snippet_target)
" For snippet_complete marker
if has('conceal')
  set conceallevel=2 concealcursor=i
endif

" -> Syntastic
let g:syntastic_check_on_open=1
let g:syntastic_aggregate_errors=1
let g:syntastic_auto_jump=1
let g:syntastic_auto_loc_list=1
let g:syntastic_error_symbol = '✗'
let g:syntastic_style_error_symbol = '✠'
let g:syntastic_warning_symbol = '∆'
let g:syntastic_style_warning_symbol = '≈'

