# Executes commands at login pre-zshrc.
# Based on https://github.com/sorin-ionescu/prezto/blob/a84ac5b0023d71c98bb28a68c550dc13f6c51945/runcoms/zprofile

# Open files in GUI
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export EDITOR='nvim'
export PAGER='less -R'
export VISUAL='nvim' # Editor to be opened from $PAGER

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Paths
## Ensure path arrays do not contain duplicates (except manpath, which needs gnuman placed at the start)
typeset -gU cdpath fpath mailpath path

BREW_PREFIX=$(hash brew 2>/dev/null && brew --prefix || /opt/homebrew/bin/brew --prefix)

## Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin # Custom home bin directory
  $HOME/.bin # bin directory from this repo
  $BREW_PREFIX/opt/coreutils/libexec/gnubin # GNU coreutils
  $BREW_PREFIX/opt/make/libexec/gnubin # GNU make
  $BREW_PREFIX/bin
  /usr/local/{bin,sbin}
  $path
)

# rust
RUST_BIN="$HOME/.cargo/bin"
if [[ -d "$RUST_BIN" ]]; then
  path=(
    $HOME/.cargo/bin # rust crates
    $path
  )
fi

# GNU coreutils man path fix
manpath=(
  /usr/local/opt/coreutils/libexec/gnuman
  $manpath
)

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# History
export HISTSIZE=500
