# Set up zinit
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ -d $ZINIT_HOME ]; then
  source $ZINIT_HOME/zinit.zsh
  zinit light Aloxaf/fzf-tab
  zinit light Tarrasch/zsh-bd
  zinit light zdharma-continuum/fast-syntax-highlighting
  zinit light zsh-users/zsh-autosuggestions

  forgit_log=fglo
  forgit_reflog=fgrl
  forgit_diff=fgd
  forgit_show=fgso
  forgit_add=fga
  forgit_reset_head=fgrh
  forgit_ignore=fgi
  forgit_attributes=fgat
  forgit_checkout_file=fgcf
  forgit_checkout_branch=fgcb
  forgit_branch_delete=fgbd
  forgit_checkout_tag=fgct
  forgit_checkout_commit=fgco
  forgit_revert_commit=fgrc
  forgit_clean=fgclean
  forgit_stash_show=fgss
  forgit_stash_push=fgsp
  forgit_cherry_pick=fgcp
  forgit_rebase=fgrb
  forgit_blame=fgbl
  forgit_fixup=fgfu

  zinit light wfxr/forgit
fi

# Load zsh modules
autoload -U colors && colors
autoload -Uz compinit && compinit

# Source everything ending in .zsh in the lib directory.
for rcfile in $DOTLIB/*.zsh; do
  source $rcfile
done

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# navi
if type navi > /dev/null; then
  eval "$(navi widget zsh)"
fi

# Tell the terminal about the working directory at each prompt.
# http://apple.stackexchange.com/a/128999
if [ "$TERM_PROGRAM" = "Apple_Terminal" ] && [ -z "$INSIDE_EMACS" ]; then
  update_terminal_cwd() {
    # Identify the directory using a "file:" scheme URL,
    # including the host name to disambiguate local vs.
    # remote connections. Percent-escape spaces.
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
  }
  PROMPT_COMMAND="update_terminal_cwd; $PROMPT_COMMAND"
fi
