# Set up zinit
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ -d $ZINIT_HOME ]; then
  source $ZINIT_HOME/zinit.zsh
  zinit light Aloxaf/fzf-tab
  zinit light Tarrasch/zsh-bd
  zinit light zdharma-continuum/fast-syntax-highlighting
  zinit light zsh-users/zsh-autosuggestions

  forgit_log=flo
  forgit_reflog=frl
  forgit_diff=fgd
  forgit_show=fso
  forgit_add=fa
  forgit_reset_head=frh
  forgit_ignore=fgi
  forgit_attributes=fat
  forgit_checkout_file=fcf
  forgit_checkout_branch=fco
  forgit_branch_delete=fbd
  forgit_checkout_tag=fct
  forgit_checkout_commit=fcc
  forgit_revert_commit=frc
  forgit_clean=fcl
  forgit_stash_show=fss
  forgit_stash_push=fsp
  forgit_cherry_pick=fcp
  forgit_rebase=frb
  forgit_blame=fbl
  forgit_fixup=ffu

  zinit light wfxr/forgit
fi

# Load zsh modules
autoload -U colors && colors
autoload -Uz compinit && compinit

# Source everything ending in .zsh in the lib directory.
for rcfile in $DOTLIB/*.zsh; do
  source $rcfile
done

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# navi
if type navi > /dev/null; then
  eval "$(navi widget zsh)"
fi

# Tell the terminal about the working directory at each prompt.
# http://apple.stackexchange.com/a/128999
if [ "$TERM_PROGRAM" = "Apple_Terminal" ] && [ -z "$INSIDE_EMACS" ]; then
  update_terminal_cwd() {
    # Identify the directory using a "file:" scheme URL,
    # including the host name to disambiguate local vs.
    # remote connections. Percent-escape spaces.
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
  }
  PROMPT_COMMAND="update_terminal_cwd; $PROMPT_COMMAND"
fi

# bun completions
[ -s "/Users/knpwrs/.bun/_bun" ] && source "/Users/knpwrs/.bun/_bun"
