onboarding = false

[keys]
prefix = "ctrl+g"

# --- config ---
reload_config = "prefix+shift+r"

# --- panes ---
split_vertical = "alt+\\"
split_horizontal = "alt+minus"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"

# --- tabs ---
new_tab = "alt+t"
rename_tab = "alt+r"
previous_tab = "alt+["
next_tab = "alt+]"

# --- spaces ---
new_workspace = "alt+shift+t"
rename_workspace = "alt+shift+r"
previous_workspace = "alt+{"
next_workspace = "alt+}"

# --- agents ---
previous_agent = "alt+p"
next_agent = "alt+n"
